# Generated by Django 2.2.5 on 2019-10-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191009_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='max_continuous_renews',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
