# Generated by Django 2.2.5 on 2019-11-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191113_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
