# Generated by Django 2.2.5 on 2019-10-25 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191025_1258'),
        ('blog', '0002_auto_20191008_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='user',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Member'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='posttag',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
