# Generated by Django 2.2.4 on 2019-09-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190819_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='status',
            field=models.IntegerField(choices=[(10, 'Approved'), (20, 'Refused'), (30, 'Waiting...')], default=30),
        ),
    ]
