# Generated by Django 2.2.5 on 2019-11-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191025_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[(10, 'Draft'), (20, 'Published'), (30, 'Withdrawn')], default='draft', max_length=10),
        ),
    ]
