# Generated by Django 2.2.5 on 2019-10-08 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('min_age', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_digital', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('native_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.Rack')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.Floor')),
            ],
        ),
        migrations.AddField(
            model_name='rack',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.Repository'),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_of_establishment', models.DateField(blank=True, null=True)),
                ('refer_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.Publication')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('DDC', models.CharField(blank=True, max_length=10, null=True)),
                ('LCC', models.CharField(blank=True, max_length=10, null=True)),
                ('NBN', models.CharField(blank=True, max_length=10, null=True)),
                ('ISBN', models.CharField(blank=True, max_length=13, null=True)),
                ('active', models.BooleanField(default=True)),
                ('checkoutable', models.BooleanField(default=True)),
                ('reservable', models.BooleanField(default=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('edition', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('copies', models.PositiveIntegerField(blank=True, null=True)),
                ('call_no', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_pages', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('age_classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.AgeClassification')),
                ('authors', models.ManyToManyField(blank=True, to='documents.Author')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.DocumentType')),
                ('editors', models.ManyToManyField(blank=True, to='documents.Editor')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.Language')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.Row')),
                ('publications', models.ManyToManyField(blank=True, to='documents.Publication')),
                ('translators', models.ManyToManyField(blank=True, to='documents.Translator')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=600)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(10, 'Approved'), (20, 'Refused'), (30, 'Waiting...')], default=30)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.Document')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
