# Generated by Django 2.2.5 on 2019-10-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.IntegerField(choices=[(10, 'Available'), (20, 'Reserved'), (30, 'Loaned'), (40, 'Lost')], default=10),
        ),
    ]
