# Generated by Django 2.2.5 on 2019-10-05 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20191005_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='slug',
        ),
    ]
