# Generated by Django 2.2.5 on 2019-10-21 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.Row'),
        ),
    ]
