# Generated by Django 2.2.5 on 2019-10-08 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.Rack')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='call_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.Row'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.Building'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='refer_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.Publication'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='repository',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.Floor'),
        ),
        migrations.AddField(
            model_name='rack',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.Repository'),
        ),
    ]
