# Generated by Django 2.2.5 on 2019-10-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20191023_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='published_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
