# Generated by Django 2.2.5 on 2019-10-25 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191025_1258'),
        ('documents', '0007_document_published_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('text', models.TextField(max_length=600)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(10, 'Approved'), (20, 'Refused'), (30, 'Waiting...')], default=30)),
            ],
        ),
        migrations.AlterField(
            model_name='ageclassification',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='building',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='editor',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='floor',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='language',
            name='native_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='rack',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='repository',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='row',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='translator',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='documentcomment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.Document'),
        ),
        migrations.AddField(
            model_name='documentcomment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Member'),
        ),
        migrations.AddField(
            model_name='documentcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.DocumentComment'),
        ),
    ]
