# Generated by Django 2.2.5 on 2019-10-29 17:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191025_1258'),
        ('documents', '0008_auto_20191025_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(blank=True, max_length=600, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(10, 'Approved'), (20, 'Refused'), (30, 'Waiting...')], default=30)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.Document')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Member')),
            ],
        ),
        migrations.DeleteModel(
            name='DocumentComment',
        ),
    ]
