# Generated by Django 2.2.5 on 2019-10-08 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('circulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='documents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Document'),
        ),
    ]
