# Generated by Django 2.2.5 on 2019-10-09 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_comment_user'),
        ('users', '0002_auto_20191009_1307'),
        ('circulation', '0003_auto_20191008_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('returned', models.BooleanField(default=False)),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.Document')),
                ('fine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='circulation.Fine')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Member')),
            ],
        ),
        migrations.AlterField(
            model_name='reserve',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Member'),
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
