# Generated by Django 2.2.5 on 2019-10-09 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191009_1307'),
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('circulation', '0004_auto_20191009_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='returned',
        ),
        migrations.CreateModel(
            name='BaseFine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Member')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.Payment')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
