# Generated by Django 2.2.5 on 2019-10-09 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20191009_1307'),
        ('accounting', '0001_initial'),
        ('circulation', '0005_auto_20191009_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='fine',
        ),
        migrations.AddField(
            model_name='fine',
            name='amount',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fine',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fine',
            name='member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='users.Member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fine',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.Payment'),
        ),
        migrations.AddField(
            model_name='fine',
            name='reason',
            field=models.IntegerField(choices=[(10, 'Overdue'), (20, 'Damage'), (30, 'Other')], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fine',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fine',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='fines',
            field=models.ManyToManyField(blank=True, to='circulation.Fine'),
        ),
        migrations.DeleteModel(
            name='BaseFine',
        ),
    ]
