# Generated by Django 2.2.5 on 2019-10-09 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0006_auto_20191009_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='documents',
            new_name='document',
        ),
        migrations.AddField(
            model_name='reserve',
            name='available_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='circulation.Issue'),
        ),
        migrations.CreateModel(
            name='Renew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='circulation.Issue')),
            ],
        ),
    ]
