# Generated by Django 2.2.5 on 2019-10-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0008_reserve_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='user',
            new_name='member',
        ),
    ]
