# Generated by Django 2.2.5 on 2019-10-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0009_auto_20191019_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='forced_expired',
            field=models.BooleanField(default=False),
        ),
    ]
