# Generated by Django 2.2.5 on 2019-10-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0010_reserve_forced_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='forced_expired',
        ),
        migrations.AddField(
            model_name='reserve',
            name='status',
            field=models.IntegerField(blank=True, choices=[(10, 'Waiting...'), (20, 'Available'), (30, 'Proceed'), (40, 'Expired'), (50, 'Expired by staff')], null=True),
        ),
    ]
