# Generated by Django 2.2.5 on 2019-11-19 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0014_auto_20191119_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fine',
            name='member',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='fines',
        ),
        migrations.AddField(
            model_name='fine',
            name='issue',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='circulation.Issue'),
            preserve_default=False,
        ),
    ]
