# Generated by Django 2.2.5 on 2019-11-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20191114_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.IntegerField(choices=[(10, 'Cash'), (20, 'Credit Card'), (30, 'Card to Card'), (40, 'Balance')]),
        ),
    ]
