# Generated by Django 2.2.5 on 2019-11-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20191114_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference_num',
            field=models.CharField(default='aaaa', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='successful',
            field=models.BooleanField(default=False),
        ),
    ]
